services:
  web:
    image: ${IMAGE_NAME:-ghcr.io/tekkifox/vortexservers_co_uk:latest}
    restart: always
    hostname: vortexservers_co_uk-web
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    env_file: 
      - stack.env
    networks:
      proxy:
networks:
  proxy:
    external: true