import type { NextRequest } from "next/server";
import { getPublicOrigin } from "@/lib/public-origin";

export function buildCmsConfig(request: NextRequest) {
  if (process.env.NODE_ENV === "production") {
    const repo = process.env.GITHUB_REPO?.trim() || "username/repo";
    const origin = getPublicOrigin(request).replace(/\/$/, "");

    return [
      "backend:",
      "  name: github",
      `  repo: ${repo}`,
      "  branch: main",
      `  base_url: ${origin}`,
      "publish_mode: editorial_workflow",
      "media_folder: public/uploads",
      "public_folder: /uploads",
      "collections:",
      "  - name: pages",
      "    label: Pages",
      "    folder: content/pages",
      "    create: true",
      "    extension: md",
      "    format: frontmatter",
      "    fields:",
      "      - label: Title",
      "        name: title",
      "        widget: string",
      "      - label: Description",
      "        name: description",
      "        widget: text",
      "        required: false",
      "      - label: Eyebrow",
      "        name: eyebrow",
      "        widget: string",
      "        required: false",
      "      - label: Primary CTA Label",
      "        name: primaryCtaLabel",
      "        widget: string",
      "        required: false",
      "      - label: Primary CTA Href",
      "        name: primaryCtaHref",
      "        widget: string",
      "        required: false",
      "      - label: Secondary CTA Label",
      "        name: secondaryCtaLabel",
      "        widget: string",
      "        required: false",
      "      - label: Secondary CTA Href",
      "        name: secondaryCtaHref",
      "        widget: string",
      "        required: false",
      "      - label: Body",
      "        name: body",
      "        widget: markdown",
    ].join("\n");
  }

  return [
    "backend:",
    "  name: git-gateway",
    "local_backend: true",
    "publish_mode: editorial_workflow",
    "media_folder: public/uploads",
    "public_folder: /uploads",
    "collections:",
    "  - name: pages",
    "    label: Pages",
    "    folder: content/pages",
    "    create: true",
    "    extension: md",
    "    format: frontmatter",
    "    fields:",
    "      - label: Title",
    "        name: title",
    "        widget: string",
    "      - label: Description",
    "        name: description",
    "        widget: text",
    "        required: false",
    "      - label: Eyebrow",
    "        name: eyebrow",
    "        widget: string",
    "        required: false",
    "      - label: Primary CTA Label",
    "        name: primaryCtaLabel",
    "        widget: string",
    "        required: false",
    "      - label: Primary CTA Href",
    "        name: primaryCtaHref",
    "        widget: string",
    "        required: false",
    "      - label: Secondary CTA Label",
    "        name: secondaryCtaLabel",
    "        widget: string",
    "        required: false",
    "      - label: Secondary CTA Href",
    "        name: secondaryCtaHref",
    "        widget: string",
    "        required: false",
    "      - label: Body",
    "        name: body",
    "        widget: markdown",
  ].join("\n");
}
